# This is a basic workflow to help you get started with Actions

name: CI CD PIPELINE FOR JAVA WEB APPLICATION

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  Install_Java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install java
        run: sudo apt-get update -y && sudo apt install openjdk-11-jdk-headless -y
      - name: Checking Java Version
        run: sudo java -version
      - name: Install Maven
        run: sudo apt-get install maven -y
      - name: Checking Maven Version
        run: mvn --version
      - name: create archive file
        run: mvn package
